name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install Swift on Linux
      uses: sersoft-gmbh/SwiftyActions@v1.3.0
      with:
        branch-name: swift-5.5-branch
        version-tag: swift-5.5-DEVELOPMENT-SNAPSHOT-2021-09-18-a
        platform: ubuntu-20.04
    - name: Build
      run: swift build
    - name: Run Tests
      run: swift test
